[[redirects]]
  from = "/register"
  to = "/register"
  status = 200
  force = true
  signed = true

[[redirects]]
  from = "/stripepayment"
  to = "/stripepayment"
  status = 200
  force = true
  signed = true

[[redirects]]
  from = "/meat-your-match"
  to = "/meat-your-match"
  status = 200
  force = true
  signed = true

[[redirects]]
  from = "/new-experience"
  to = "/new-experience"
  status = 200
  force = true
  signed = true

[[redirects]]
  from = "/my-experiences"
  to = "/my-experiences"
  status = 200
  force = true
  signed = true

[[redirects]]
  from = "/edit-experience/:id"
  to = "/edit-experience/:id"
  status = 200
  query = {id = ":id"}
  force = true
  signed = true

[[redirects]]
  from = "/butchers"
  to = "/butchers"
  status = 200
  force = true
  signed = true

[[redirects]]
  from = "/butchers/:id"
  to = "/butchers/:id"
  status = 200
  query = {id = ":id"}
  force = true
  signed = true

[[redirects]]
  from = "/community"
  to = "/community"
  status = 200
  force = true
  signed = true
